swupdate: fix dtb paths on r36
With r36 the DTBFILE is no longer found, and attempts to build fail
with
```
ERROR: swupdate cannot find tegra234-p3768-0000+p3767-0005-nv.dtb image file
DEBUG: Python function do_swuimage finished
```

Add a build dependency on DTB_EXTRA_DEPS to match what other recipes
do when referencing DTBFILE.

Provide the full DTBPATH to the DTBFILE in the sysroot as the image
dependency, then reference DTBFILE in the sw-description as done
previously.